### ISSUE TITLE
Bayar Lepas 30hb Jun?

### ISSUE THREAD

**Issue by linuxmalaysia** [ApOgEE/TempahTeeGit#40]
Nak bayar lepas 30hb Jun? Ini tempah dulu?

**Comment by ApOgEE** [comment]
yes, bayar lepas tutup pre-order, next week. saya akan bagi payment instruction pada semua. Hanya siapa yang bayar sahaja akan dikira. siapa yg missed bayaran takkan dapat baju dia sebab saya akan print ngam2 je

**Comment by ApOgEE** [comment]
boleh follow issue ni @xspinners

**Comment by tedbundyjr** [comment]
osem!

**Comment by snzmnrdn** [comment]
alright.

**Comment by ApOgEE** [comment]
Saya dah emailkan borang bayaran pada semua yang terlibat. Jika ada yang tak terima email dari kedaigeek.com, sila hubungi saya segera. Saya beri tempoh 2 hari dari sekarang untuk jelaskan bayaran. Siapa yang lewat bayar, tidak akan dapat baju. Terima kasih.
